# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3969177378bc63842521ac57ac80b71bfcb9e7959823dfd8df548d5707b77f25a2be0ec7bcab3a9152cfe8312ed333ed149c1867b01f8f56cd8dd479184e2cb6

test:
  secret_key_base: b78f7702f445ec3a02d01d3732f710899fd7b93d24f8a265b00f66f7aa0f555bfae7e39379d8ed0bba3e668ec81e069a5a69b6104dd7b1191ad73e1f2c9ed07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
